import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { test } from "node:test";

function source(relativePath) {
  return readFileSync(new URL(relativePath, import.meta.url), "utf8");
}

test("activitatea Blocuri și bridge-ul ei dedicat sunt eliminate complet", () => {
  assert.equal(
    existsSync(new URL("../src/lib/components/creation/BlocksWorkspace.svelte", import.meta.url)),
    false,
  );
  assert.equal(
    existsSync(new URL("../src-tauri/permissions/autogenerated/read_native_block_registry.toml", import.meta.url)),
    false,
  );

  const frontend = [
    source("../src/lib/workbench/contracts.ts"),
    source("../src/lib/components/workbench/ActivityRail.svelte"),
    source("../src/lib/components/workspace/WorkspaceCenterArea.svelte"),
    source("../src/lib/i18n/ui-terms.ts"),
  ].join("\n");
  const rust = [
    source("../src-tauri/src/kernel/workbench/model.rs"),
    source("../src-tauri/src/kernel/command_center/search.rs"),
  ].join("\n");

  assert.doesNotMatch(frontend, /BlocksWorkspace|id:\s*"blocks"|\|\s*"blocks"/);
  assert.doesNotMatch(rust, /WorkbenchActivity::Blocks|^\s*Blocks,\s*$/m);
  assert.match(rust, /alias = "themes", alias = "blocks"/);
});

test("Blocurile rămân în catalogul Adaugă și proprietățile lor rămân în Inspector", () => {
  const panel = source("../src/lib/components/project/InsertCatalogPanel.svelte");
  const catalog = source("../src-tauri/src/kernel/insert_catalog.rs");
  const inspector = source("../src/lib/components/inspector/BlockPropertiesPane.svelte");
  const commands = source("../src-tauri/src/commands/blocks.rs");
  const registry = source("../src-tauri/src/tauri_command_registry.rs");
  const frontendIo = source("../src/lib/blocks/io.ts");

  assert.match(panel, /id:\s*"block", label:\s*"Blocuri"/);
  assert.match(panel, /id:\s*"dynamicWidget", label:\s*"Dinamic"/);
  assert.match(catalog, /native_block_registry_snapshot\(\)/);
  assert.match(catalog, /fn block_group\(/);
  assert.match(inspector, /readUiBlockGraph/);
  assert.match(inspector, /DynamicWidgetPropertiesEditor/);
  assert.doesNotMatch(`${commands}\n${registry}\n${frontendIo}`, /read_native_block_registry/);
});

test("bindingul dinamic experimental dispare, iar DynamicWidget rămâne canonic", () => {
  const legacySurface = [
    source("../src/lib/preview/contracts.ts"),
    source("../src/lib/tera/model.ts"),
    source("../src/lib/state/tera-actions-controller.ts"),
    source("../src/lib/state/preview-tera-insert-controller.ts"),
    source("../src/lib/state/tera-palette-drag-controller.ts"),
    source("../src-tauri/src/preview/bridge/07_drag_drop.js"),
    source("../src-tauri/src/project_model/tera_insert_engine.rs"),
    source("../src-tauri/src/kernel/content_models/usage_index.rs"),
    source("../src-tauri/src/kernel/content_models/mutation_plan.rs"),
    source("../src-tauri/src/kernel/content_models/rewrite/templates.rs"),
  ].join("\n");
  const widget = source("../src-tauri/src/kernel/dynamic_widgets.rs");
  const catalog = source("../src-tauri/src/kernel/insert_catalog.rs");

  assert.doesNotMatch(legacySurface, /ProjectDynamicFieldBinding|dynamicBinding|dynamic_binding|pana:dynamic/);
  assert.match(widget, /pana:widget/);
  assert.match(widget, /pub enum DynamicWidgetProperties/);
  assert.match(catalog, /InsertCatalogCategory::DynamicWidget/);
});
