import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

function source(path) {
  return readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
}

test("CSS panel has one Rust/ProjectWorkspace write authority", () => {
  const inspector = source("src/lib/components/InspectorPane.svelte");
  const app = source("src/lib/state/app.svelte.ts");
  const design = source("src/lib/components/creation/DesignSystemWorkspace.svelte");
  const sourceSync = source("src/lib/css/source-sync.ts");

  assert.match(inspector, /setCssRuleAtViewport/);
  assert.match(inspector, /setPageCssRuleAtViewport/);
  assert.match(inspector, /setReusableCssRuleAtViewport/);
  assert.doesNotMatch(inspector, /setScssVariable|VariablesPane|inspectorTab === "vars"/);
  assert.match(app, /async updateDesignSystemVariable[\s\S]*setScssVariable/);
  assert.match(design, /app\.updateDesignSystemVariable/);
  assert.match(inspector, /stageCssRuleMutation/);
  assert.match(inspector, /flushStagedCssPanelMutations/);
  assert.match(inspector, /registerEditFlushHandler\("inspector-css-workspace"/);
  assert.doesNotMatch(inspector, /applyCssPanelEditToOpenSource/);
  assert.doesNotMatch(app, /applyCssPanelEditToOpenSource|projectOpenSourceInspectorCssMutation/);
  assert.doesNotMatch(sourceSync, /upsertCssPropertyInSource|upsertDeclarationInBlock/);
});

test("reusable template CSS has a deterministic Rust owner and consumer delivery", () => {
  const theme = source("src-tauri/src/zola_theme.rs");
  const rust = source("src-tauri/src/commands/css.rs");
  const stylesheet = source("src-tauri/src/css/page/stylesheet.rs");
  const io = source("src/lib/project/io.ts");
  const inspector = source("src/lib/components/InspectorPane.svelte");
  const pane = source("src/lib/components/inspector/panes/CssPane.svelte");
  const registry = source("src-tauri/src/tauri_command_registry.rs");

  assert.match(theme, /pub fn reusable_scss_relative_path/);
  assert.match(theme, /partials\/listing-items/);
  assert.match(rust, /pub fn set_reusable_css_rule_at_viewport/);
  assert.match(rust, /resolve_template_workbench_plan/);
  assert.match(rust, /TemplateWorkbenchDependencyKind::Includes/);
  assert.match(rust, /reusable_scoped_candidates/);
  assert.match(stylesheet, /prepare_reusable_consumer_stylesheet_source/);
  assert.match(io, /"set_reusable_css_rule_at_viewport"/);
  assert.match(inspector, /pageTarget\?\.targetKind === "reusable"/);
  assert.match(pane, /pageCssTarget\?\.targetKind === "reusable"/);
  assert.match(pane, /pageCssTarget\.consumerFiles/);
  assert.match(pane, /inspector-css-reusable-consumers/);
  assert.doesNotMatch(pane, /inspector-css-target-file|css-target-note/);
  assert.match(registry, /set_reusable_css_rule_at_viewport/);
});

test("CSS inspector context is resolved atomically by Rust without the legacy manual search", () => {
  const rust = source("src-tauri/src/commands/css.rs");
  const coordinator = source("src-tauri/src/kernel/selection_coordinator.rs");
  const registry = source("src-tauri/src/tauri_command_registry.rs");
  const io = source("src/lib/project/io.ts");
  const inspector = source("src/lib/components/InspectorPane.svelte");
  const pane = source("src/lib/components/inspector/panes/CssPane.svelte");
  const permission = source(
    "src-tauri/permissions/autogenerated/resolve_css_inspector_context.toml",
  );
  const production = [rust, registry, io, inspector, pane].join("\n");

  assert.match(rust, /pub fn resolve_css_inspector_context/);
  assert.match(rust, /with_selection_target/);
  assert.match(rust, /workspace_revision != expected_workspace_revision/);
  assert.match(rust, /CssInspectorContextState::Ambiguous/);
  assert.match(rust, /collect_current_project_style_sources/);
  assert.match(coordinator, /pub fn with_selection_target/);
  assert.match(registry, /resolve_css_inspector_context/);
  assert.match(permission, /allow-resolve-css-inspector-context/);
  assert.match(io, /export async function resolveCssInspectorContext/);
  assert.match(io, /resolution\.selectionRevision !== expectedRevision/);
  assert.match(inspector, /await resolveCssInspectorContext/);
  assert.match(pane, /resolution\?\.state === "ambiguous"/);
  assert.doesNotMatch(pane, /inspector-css-search-all|searchClassInAllFiles/);
  assert.doesNotMatch(
    production,
    /find_class_in_scss|get_class_rules_at_viewport|get_css_rule_context|resolve_page_css_target|findClassInScss|getClassRulesAtViewport|getCssRuleContext|resolvePageCssTarget/,
  );
});

test("Inspectorul începe cu conținutul util, fără antet redundant", () => {
  const inspector = source("src/lib/components/InspectorPane.svelte");

  assert.doesNotMatch(inspector, /<h2>Inspector<\/h2>|pane-title-tag|vars-toggle-btn/);
  assert.match(inspector, /<aside[\s\S]*\{#if hasTeraSelection\}/);
});

test("CSS receipt projects exact FileBuffer snapshots into CodeMirror state", () => {
  const types = source("src/lib/types.ts");
  const io = source("src/lib/project/io.ts");
  const app = source("src/lib/state/app.svelte.ts");

  assert.match(types, /CssMutationAuthorityReceipt[\s\S]*documents: WorkspaceDocumentProjection\[\]/);
  assert.match(io, /authority\.schemaVersion !== 2/);
  assert.match(io, /written\.contents !== snapshot\.text/);
  assert.match(app, /rebaseFileBufferDraftSyncProjection\(projection\.relativePath, projection\.snapshot\)/);
  assert.match(app, /this\.source = projection\.snapshot\.text/);
});

test("toggle-ul activ emite delete intent, iar un no-op recitește adevărul canonic", () => {
  const segmented = source("src/lib/components/inspector/controls/SegmentedControl.svelte");
  const app = source("src/lib/state/app.svelte.ts");

  assert.match(segmented, /toggleable && value === nextValue \? "" : nextValue/);
  assert.match(
    app,
    /authority\.status === "noop"[\s\S]*this\.notifyCssSourceChanged\(\)/,
  );
});

test("proiecția workspace cere o origine Preview navigabilă, nu doar un iframe", () => {
  const app = source("src/lib/state/app.svelte.ts");
  const previewController = source("src/lib/state/preview-controller.ts");
  const canProject = app.slice(
    app.indexOf("\n  canProjectWorkspacePreview()"),
    app.indexOf("markPreviewLive", app.indexOf("\n  canProjectWorkspacePreview()")),
  );

  assert.match(canProject, /hasMountedCanvasProjectionSurface\(\)/);
  assert.match(canProject, /scannedProject\?\.previewBaseUrl/);
  assert.match(canProject, /previewSrc !== "about:blank"/);
  assert.match(
    previewController,
    /canvasSurfaceElement === host\.previewFrame[\s\S]*canvasSurfaceElement\.contentWindow/,
  );
});

test("all ten CSS sections share the explicit property edit contract", () => {
  const editor = source("src/lib/components/inspector/ClassEditor.svelte");
  const sections = [
    "Typography", "Background", "Spacing", "Layout", "Position",
    "Size", "Border", "Shadow", "Transform", "Effects",
  ];
  for (const section of sections) {
    assert.match(editor, new RegExp(`<${section}Section\\s`), section);
  }
  assert.equal((editor.match(/edit=\{cssPropertyEdit\}/g) ?? []).length, sections.length);
  assert.doesNotMatch(editor, /setValue=\{updateProperty\}/);
});

test("CSS edits use explicit draft, commit and cancel boundaries", () => {
  const inspector = source("src/lib/components/InspectorPane.svelte");
  const contract = source("src/lib/inspector/css-property-edit.ts");
  const propInput = source("src/lib/components/inspector/controls/PropInput.svelte");
  const typography = source("src/lib/components/inspector/sections/TypographySection.svelte");

  assert.match(contract, /draft: \(property: string, value: string\)/);
  assert.match(contract, /draftMany: \(properties: Readonly<Record<string, string>>\)/);
  assert.match(contract, /commit: \(property: string, value\?: string\)/);
  assert.match(contract, /cancel: \(property: string\)/);
  assert.match(contract, /commitMany:/);
  assert.match(contract, /cancelMany:/);
  assert.match(inspector, /function draftCssProperty/);
  assert.match(inspector, /function commitCssProperty/);
  assert.match(inspector, /function cancelCssProperty/);
  assert.match(inspector, /restoreCssPendingValueBaseline/);
  assert.doesNotMatch(inspector, /addEventListener\("click", scheduleStagedCssPanelFlush\)/);
  assert.doesNotMatch(inspector, /addEventListener\("change", scheduleStagedCssPanelFlush\)/);
  assert.doesNotMatch(inspector, /<svelte:window onpointerup=\{scheduleStagedCssPanelFlush\}/);

  assert.match(propInput, /oncommit\?\.\(draftValue\)/);
  assert.match(propInput, /oncancel\?\.\(\)/);
  assert.match(typography, /edit\.continuous\("font-size"\)/);
  assert.match(typography, /edit\.commit\("text-align", v\)/);
});

test("CSS refresh and class switching keep the previous complete projection until atomic replacement", () => {
  const inspector = source("src/lib/components/InspectorPane.svelte");
  const pane = source("src/lib/components/inspector/panes/CssPane.svelte");
  const classSwitch = inspector.slice(
    inspector.indexOf("async function selectClassForCss"),
    inspector.indexOf("function selectCssVariant"),
  );

  assert.match(inspector, /\{ retainProjection: true \}/);
  assert.match(inspector, /hasStableCssInspectorProjection/);
  assert.match(inspector, /loadingClassRules = !retainProjection/);
  assert.match(inspector, /presentedCssSelector/);
  assert.match(inspector, /cssProjectionTransitioning/);
  assert.match(pane, /inert=\{projectionTransitioning\}/);
  assert.match(classSwitch, /const retainProjection = hasStableCssInspectorProjection/);
  assert.match(
    classSwitch,
    /if \(resolution\.state === "ambiguous" \|\| !resolution\.target\) \{\s*applyCssInspectorResolution/,
  );
  assert.doesNotMatch(
    classSwitch.slice(
      classSwitch.indexOf("const allowed = await onCssCodeTargetChange"),
      classSwitch.indexOf("return allowed"),
    ),
    /applyCssInspectorResolution/,
  );
  assert.match(inspector, /cssInspectorSubjectKey\(nextSelectionIdentity\)/);
  assert.match(inspector, /selectionSummary=\{presentedInspectorSelectionSummary\}/);
});

test("CSS reads are latest-selection-wins and stale completions stay silent", () => {
  const inspector = source("src/lib/components/InspectorPane.svelte");
  const load = inspector.slice(
    inspector.indexOf("async function loadRulesForClass"),
    inspector.indexOf("async function selectClassForCss"),
  );
  const beforeInvoke = load.slice(0, load.indexOf("await resolveCssInspectorContext"));

  assert.match(inspector, /const selectionRevision = selectionSnapshot\?\.selectionRevision \?\? 0/);
  assert.doesNotMatch(beforeInvoke, /isCurrentCssInspectorRead/);
  assert.match(inspector, /isCurrentCssInspectorRead\(expectedSelection\)/);
  assert.match(
    inspector,
    /catch \(error\)[\s\S]*!isCurrentCssInspectorRead\(expectedSelection\)[\s\S]*inspector-css-read-failed/,
  );
});

test("Undo quiesces CSS reads and focus errors until history projection settles", () => {
  const inspector = source("src/lib/components/InspectorPane.svelte");
  const workspace = source("src/lib/components/workspace/WorkspaceInspectorArea.svelte");
  const app = source("src/lib/state/app.svelte.ts");

  assert.match(inspector, /if \(historyProjectionQuiesced\) return;/);
  assert.match(
    workspace,
    /historyProjectionQuiesced=\{app\.kernelUndoRedoFrontendQuiesceActive[\s\S]*app\.kernelUndoRedoFrontendLeaseActive\}/,
  );
  assert.match(
    app,
    /async selectCssFocusFromInspector[\s\S]*kernelUndoRedoFrontendQuiesceActive[\s\S]*kernelUndoRedoFrontendLeaseActive[\s\S]*return false/,
  );
});

test("CSS focus promotes the current Canvas revision before sending a Rust selection intent", () => {
  const inspector = source("src/lib/components/InspectorPane.svelte");
  const app = source("src/lib/state/app.svelte.ts");
  const classIntent = inspector.slice(
    inspector.indexOf("async function selectClassForCss"),
    inspector.indexOf("function selectCssVariant"),
  );
  const focusIntent = app.slice(
    app.indexOf("async selectCssFocusFromInspector"),
    app.indexOf("selectJsBehaviorFromCode"),
  );

  assert.doesNotMatch(
    classIntent.slice(0, classIntent.indexOf("resolveCssInspectorContext")),
    /classRules = \[\]|cssRuleContext = null|cssInspectorResolution = null/,
  );
  assert.match(focusIntent, /activeCanvasIdentity\?\.workspaceRevision !== expectedWorkspaceRevision/);
  assert.match(focusIntent, /projectLatestProjectWorkspacePreview/);
  assert.match(focusIntent, /minimumWorkspaceRevision: expectedWorkspaceRevision/);
  assert.match(focusIntent, /refreshEditorNavigationSnapshot/);
  assert.match(focusIntent, /stableAnchorMatches/);
  assert.match(focusIntent, /expectedSelectionRevision = currentSelection\.selectionRevision/);
});

test("structured compound editors preserve unsupported values in raw mode", () => {
  const background = source("src/lib/components/inspector/sections/BackgroundSection.svelte");
  const gradient = source("src/lib/components/inspector/controls/GradientEditor.svelte");
  const shadows = source("src/lib/components/inspector/sections/ShadowSection.svelte");

  assert.match(background, /background\.shorthand/);
  assert.match(background, /inspector-background-opaque-description/);
  assert.match(background, /serializeBackgroundLonghands/);
  assert.match(gradient, /inspector-background-gradient-css-source/);
  assert.match(gradient, /parseCssGradient/);
  assert.match(shadows, /boxStructured/);
  assert.match(shadows, /textStructured/);
  assert.match(shadows, /t\("inspector-shadow-complex"\)/);
});

test("background editing is Rust-first, layered and committed as one property set", () => {
  const rustModel = source("src-tauri/src/css/background.rs");
  const viewport = source("src-tauri/src/css/viewport.rs");
  const inspector = source("src/lib/components/InspectorPane.svelte");
  const background = source("src/lib/components/inspector/sections/BackgroundSection.svelte");
  const typography = source("src/lib/components/inspector/sections/TypographySection.svelte");
  const legacyEditor = new URL("../src/lib/components/inspector/sections/ColorsSection.svelte", import.meta.url);

  assert.match(rustModel, /pub struct CssBackground/);
  assert.match(rustModel, /pub struct CssBackgroundLayer/);
  assert.match(rustModel, /split_top_level_commas/);
  assert.match(rustModel, /pub fn to_longhands/);
  assert.match(viewport, /pub background: CssBackground/);
  assert.match(inspector, /function draftCssProperties/);
  assert.match(inspector, /stageCssRuleMutation\(mutation, property, value/);
  assert.match(background, /BACKGROUND_LONGHAND_PROPERTIES/);
  assert.match(background, /edit\.commitMany\(properties\)/);
  assert.match(background, /moveLayer/);
  assert.match(background, /duplicateLayer/);
  assert.match(typography, /edit\.continuous\("color"\)/);
  assert.equal(existsSync(legacyEditor), false);
});
