import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

function source(path) {
  return readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
}

test("CSS contracts and IPC have one domain-owned frontend path", () => {
  const contracts = source("src/lib/css/contracts.ts");
  const mutationContract = source("src/lib/css/mutation-contract.ts");
  const cssIo = source("src/lib/css/io.ts");

  assert.match(contracts, /export type CssRuleContext/);
  assert.doesNotMatch(contracts, /export type \{/);
  assert.match(mutationContract, /export type CssMutationAuthorityReceipt/);
  assert.match(cssIo, /export async function resolveCssInspectorContext/);
  assert.equal(existsSync(new URL("../src/lib/types.ts", import.meta.url)), false);
  assert.doesNotMatch(cssIo, /\bsetCssRule\b|\bcleanupPageCssContract\b|"set_css_rule"|"cleanup_page_css_contract"/);
});

test("CSS panel has one Rust/ProjectWorkspace write authority", () => {
  const inspector = source("src/lib/components/inspector/CssInspectorCoordinator.svelte");
  const queue = source("src/lib/inspector/css-inspector-mutation-queue.ts");
  const service = source("src/lib/css/workspace-service.ts");
  const application = source("src/lib/components/application/ApplicationWorkspace.svelte");
  const controller = source("src/lib/state/inspector-css-controller.ts");
  const design = source("src/lib/components/creation/design-system/DesignTokensWorkspace.svelte");
  const sourceSync = source("src/lib/css/source-sync.ts");

  assert.match(queue, /setCssRuleAtViewport/);
  assert.match(queue, /setPageCssRuleAtViewport/);
  assert.match(queue, /setReusableCssRuleAtViewport/);
  assert.doesNotMatch(inspector, /setScssVariable|VariablesPane|inspectorTab === "vars"/);
  assert.match(controller, /export async function updateDesignSystemVariable[\s\S]*setScssVariable/);
  assert.match(service, /updateVariable[\s\S]*updateDesignSystemVariable\(this\.inspector/);
  assert.match(design, /updateVariable/);
  assert.match(application, /updateVariable: \(variable, value\) => cssWorkspace\.updateVariable/);
  assert.match(queue, /private stage\(/);
  assert.match(queue, /async flushForRegistry\(/);
  assert.match(inspector, /registerEditFlushHandler\(\s*"inspector-css-workspace"/);
  assert.doesNotMatch(inspector, /setCssRuleAtViewport|setPageCssRuleAtViewport|setReusableCssRuleAtViewport/);
  assert.doesNotMatch(inspector, /applyCssPanelEditToOpenSource/);
  assert.doesNotMatch(service, /applyCssPanelEditToOpenSource|projectOpenSourceInspectorCssMutation/);
  assert.doesNotMatch(sourceSync, /upsertCssPropertyInSource|upsertDeclarationInBlock/);
  assert.doesNotMatch(controller, /AppState|as unknown as|as AppState/);
});

test("reusable template CSS has a deterministic Rust owner and consumer delivery", () => {
  const theme = source("src-tauri/src/zola_theme.rs");
  const rust = source("src-tauri/src/commands/css.rs");
  const stylesheet = source("src-tauri/src/css/page/stylesheet.rs");
  const io = source("src/lib/css/io.ts");
  const inspector = source("src/lib/components/inspector/CssInspectorCoordinator.svelte");
  const queue = source("src/lib/inspector/css-inspector-mutation-queue.ts");
  const pane = source("src/lib/components/inspector/panes/CssPane.svelte");
  const registry = source("src-tauri/src/tauri_command_registry.rs");

  assert.match(theme, /pub fn reusable_scss_relative_path/);
  assert.match(theme, /partials\/listing-items/);
  assert.match(rust, /pub fn set_reusable_css_rule_at_viewport/);
  assert.match(rust, /resolve_template_workbench_plan/);
  assert.match(rust, /TemplateWorkbenchDependencyKind::Includes/);
  assert.match(rust, /reusable_scoped_candidates/);
  assert.match(stylesheet, /prepare_reusable_consumer_stylesheet_source/);
  assert.match(io, /"set_reusable_css_rule_at_viewport"/);
  assert.match(queue, /pageTarget\?\.targetKind === "reusable"/);
  assert.match(pane, /pageCssTarget\?\.targetKind === "reusable"/);
  assert.match(pane, /pageCssTarget\.consumerFiles/);
  assert.match(pane, /inspector-css-reusable-consumers/);
  assert.doesNotMatch(pane, /inspector-css-target-file|css-target-note/);
  assert.match(registry, /set_reusable_css_rule_at_viewport/);
});

test("CSS inspector context is resolved atomically by Rust without the legacy manual search", () => {
  const rust = source("src-tauri/src/commands/css.rs");
  const coordinator = source("src-tauri/src/kernel/selection_coordinator.rs");
  const registry = source("src-tauri/src/tauri_command_registry.rs");
  const io = source("src/lib/css/io.ts");
  const inspector = source("src/lib/components/inspector/CssInspectorCoordinator.svelte");
  const reader = source("src/lib/inspector/css-inspector-reader.ts");
  const pane = source("src/lib/components/inspector/panes/CssPane.svelte");
  const permission = source(
    "src-tauri/permissions/autogenerated/resolve_css_inspector_context.toml",
  );
  const production = [rust, registry, io, inspector, pane].join("\n");

  assert.match(rust, /pub fn resolve_css_inspector_context/);
  assert.match(rust, /with_selection_target/);
  assert.match(rust, /workspace_revision != expected_workspace_revision/);
  assert.match(rust, /CssInspectorContextState::Ambiguous/);
  assert.match(rust, /collect_current_project_style_sources/);
  assert.match(coordinator, /pub fn with_selection_target/);
  assert.match(registry, /resolve_css_inspector_context/);
  assert.match(permission, /allow-resolve-css-inspector-context/);
  assert.match(io, /export async function resolveCssInspectorContext/);
  assert.match(io, /resolution\.selectionRevision !== expectedRevision/);
  assert.match(reader, /resolveCssInspectorContext/);
  assert.match(pane, /resolution\?\.state === "ambiguous"/);
  assert.doesNotMatch(pane, /inspector-css-search-all|searchClassInAllFiles/);
  assert.doesNotMatch(
    production,
    /find_class_in_scss|get_class_rules_at_viewport|get_css_rule_context|resolve_page_css_target|findClassInScss|getClassRulesAtViewport|getCssRuleContext|resolvePageCssTarget/,
  );
});

test("Inspectorul începe cu conținutul util, fără antet redundant", () => {
  const inspector = source("src/lib/components/InspectorPane.svelte");

  assert.doesNotMatch(inspector, /<h2>Inspector<\/h2>|pane-title-tag|vars-toggle-btn/);
  assert.match(inspector, /<aside[\s\S]*\{#if hasTeraSelection\}/);
});

test("CSS receipt projects exact FileBuffer snapshots into CodeMirror state", () => {
  const contract = source("src/lib/css/mutation-contract.ts");
  const io = source("src/lib/css/io.ts");
  const service = source("src/lib/css/workspace-service.ts");
  const controller = source("src/lib/state/inspector-css-controller.ts");

  assert.match(contract, /CssMutationAuthorityReceipt[\s\S]*documents: WorkspaceDocumentProjection\[\]/);
  assert.match(io, /authority\.schemaVersion !== 2/);
  assert.match(io, /written\.contents !== snapshot\.text/);
  assert.match(controller, /rebaseFileBufferDraftSyncProjection\(projection\.relativePath, projection\.snapshot\)/);
  assert.match(controller, /host\.source\.source = projection\.snapshot\.text/);
  assert.match(service, /projectCommittedMutation[\s\S]*projectCommittedInspectorCssMutation/);
});

test("toggle-ul activ emite delete intent, iar un no-op recitește adevărul canonic", () => {
  const segmented = source("src/lib/components/inspector/controls/SegmentedControl.svelte");
  const controller = source("src/lib/state/inspector-css-controller.ts");

  assert.match(segmented, /toggleable && value === nextValue \? "" : nextValue/);
  assert.match(
    controller,
    /authority\.status === "noop"[\s\S]*host\.notifyCssSourceChanged\(\)/,
  );
});

test("proiecția workspace cere o origine Preview navigabilă, nu doar un iframe", () => {
  const preview = source("src/lib/preview/workspace-state.svelte.ts");
  const previewController = source("src/lib/state/preview-controller.ts");
  const canProject = preview.slice(
    preview.indexOf("\n  canProjectWorkspacePreview()"),
    preview.indexOf("\n  markLive", preview.indexOf("\n  canProjectWorkspacePreview()")),
  );

  assert.match(canProject, /this\.hasMountedSurface\(\)/);
  assert.match(canProject, /project\?\.previewBaseUrl/);
  assert.match(canProject, /this\.src !== "about:blank"/);
  assert.match(
    previewController,
    /host\.surface\.canvasElement === host\.surface\.frame[\s\S]*host\.surface\.canvasElement\.contentWindow/,
  );
});

test("all ten CSS sections share the explicit property edit contract", () => {
  const editor = source("src/lib/components/inspector/ClassEditor.svelte");
  const sections = [
    "Typography", "Background", "Spacing", "Layout", "Position",
    "Size", "Border", "Shadow", "Transform", "Effects",
  ];
  for (const section of sections) {
    assert.match(editor, new RegExp(`<${section}Section\\s`), section);
  }
  assert.equal((editor.match(/edit=\{cssPropertyEdit\}/g) ?? []).length, sections.length);
  assert.doesNotMatch(editor, /setValue=\{updateProperty\}/);
});

test("CSS edits use explicit draft, commit and cancel boundaries", () => {
  const inspector = source("src/lib/components/inspector/CssInspectorCoordinator.svelte");
  const queue = source("src/lib/inspector/css-inspector-mutation-queue.ts");
  const contract = source("src/lib/inspector/css-property-edit.ts");
  const propInput = source("src/lib/components/inspector/controls/PropInput.svelte");
  const typography = source("src/lib/components/inspector/sections/TypographySection.svelte");

  assert.match(contract, /draft: \(property: string, value: string\)/);
  assert.match(contract, /draftMany: \(properties: Readonly<Record<string, string>>\)/);
  assert.match(contract, /commit: \(property: string, value\?: string\)/);
  assert.match(contract, /cancel: \(property: string\)/);
  assert.match(contract, /commitMany:/);
  assert.match(contract, /cancelMany:/);
  assert.match(queue, /private draftProperty\(/);
  assert.match(queue, /private commitProperty\(/);
  assert.match(queue, /private cancelProperty\(/);
  assert.match(queue, /restoreCssPendingValueBaseline/);
  assert.doesNotMatch(inspector, /addEventListener\("click", scheduleStagedCssPanelFlush\)/);
  assert.doesNotMatch(inspector, /addEventListener\("change", scheduleStagedCssPanelFlush\)/);
  assert.doesNotMatch(inspector, /<svelte:window onpointerup=\{scheduleStagedCssPanelFlush\}/);

  assert.match(propInput, /oncommit\?\.\(draftValue\)/);
  assert.match(propInput, /oncancel\?\.\(\)/);
  assert.match(typography, /edit\.continuous\("font-size"\)/);
  assert.match(typography, /edit\.commit\("text-align", v\)/);
});

test("CSS refresh and class switching keep the previous complete projection until atomic replacement", () => {
  const inspector = source("src/lib/components/inspector/CssInspectorCoordinator.svelte");
  const reader = source("src/lib/inspector/css-inspector-reader.ts");
  const state = source("src/lib/inspector/css-inspector-state.svelte.ts");
  const pane = source("src/lib/components/inspector/panes/CssPane.svelte");
  const classSwitch = reader.slice(
    reader.indexOf("async selectClass"),
    reader.indexOf("captureCurrentSelection"),
  );

  assert.match(reader, /this\.state\.hasStableProjection\(expectedSelection\)/);
  assert.match(state, /this\.loading = !retainProjection/);
  assert.match(state, /get presentedSelector\(\)/);
  assert.match(state, /get projectionTransitioning\(\)/);
  assert.match(pane, /inert=\{projectionTransitioning\}/);
  assert.match(classSwitch, /const retainProjection = this\.state\.hasStableProjection/);
  assert.match(
    classSwitch,
    /if \(resolution\.state === "ambiguous" \|\| !resolution\.target\) \{\s*this\.applyResolution/,
  );
  assert.doesNotMatch(
    classSwitch.slice(
      classSwitch.indexOf("const allowed = await this.dependencies.changeCodeTarget"),
      classSwitch.indexOf("return allowed"),
    ),
    /applyResolution/,
  );
  assert.match(reader, /cssInspectorSubjectKey\(expectedSelection\)/);
  assert.match(inspector, /selectionSummary=\{selectionSummary\}/);
});

test("CSS reads are latest-selection-wins and stale completions stay silent", () => {
  const reader = source("src/lib/inspector/css-inspector-reader.ts");
  const load = reader.slice(
    reader.indexOf("private async load"),
    reader.indexOf("private resolve"),
  );
  const beforeInvoke = load.slice(0, load.indexOf("await this.resolve"));

  assert.doesNotMatch(beforeInvoke, /isCurrentCssInspectorRead/);
  assert.match(reader, /cssInspectorReadIsCurrent\(expectedSelection, this\.captureSelection\(current\)\)/);
  assert.match(
    load,
    /catch \(cause\)[\s\S]*!this\.readIsCurrent[\s\S]*kind: "readFailed"/,
  );
});

test("Undo quiesces CSS reads and focus errors until history projection settles", () => {
  const reader = source("src/lib/inspector/css-inspector-reader.ts");
  const workspace = source("src/lib/components/workspace/WorkspaceInspectorArea.svelte");
  const application = source("src/lib/components/application/ApplicationWorkspace.svelte");
  const navigation = source("src/lib/editor/source-navigation-service.ts");

  assert.match(reader, /if \(input\.historyProjectionQuiesced\)/);
  assert.match(
    application,
    /historyProjectionQuiesced: historyOperation\.quiesceActive[\s\S]*historyOperation\.leaseActive/,
  );
  assert.match(
    navigation,
    /selectCssFocus[\s\S]*this\.historyLocked\(\)[\s\S]*return false/,
  );
});

test("CSS focus promotes the current Canvas revision before sending a Rust selection intent", () => {
  const reader = source("src/lib/inspector/css-inspector-reader.ts");
  const navigation = source("src/lib/editor/source-navigation-service.ts");
  const classIntent = reader.slice(
    reader.indexOf("async selectClass"),
    reader.indexOf("captureCurrentSelection"),
  );
  const focusIntent = navigation.slice(
    navigation.indexOf("async selectCssFocus("),
    navigation.indexOf("async openCssSource", navigation.indexOf("async selectCssFocus(")),
  );

  assert.doesNotMatch(
    classIntent.slice(0, classIntent.indexOf("await this.resolve")),
    /resetProjection/,
  );
  assert.match(focusIntent, /preview\.activeIdentity\?\.workspaceRevision !== expectedWorkspaceRevision/);
  assert.match(focusIntent, /this\.dependencies\.projectLatestPreview/);
  assert.match(focusIntent, /minimumWorkspaceRevision: expectedWorkspaceRevision/);
  assert.match(focusIntent, /selectionSession\.refreshNavigationSnapshot/);
  assert.match(focusIntent, /stableAnchorMatches/);
  assert.match(focusIntent, /expectedSelectionRevision = currentSelection\.selectionRevision/);
});

test("structured compound editors preserve unsupported values in raw mode", () => {
  const background = source("src/lib/components/inspector/sections/BackgroundSection.svelte");
  const gradient = source("src/lib/components/inspector/controls/GradientEditor.svelte");
  const shadows = source("src/lib/components/inspector/sections/ShadowSection.svelte");

  assert.match(background, /background\.shorthand/);
  assert.match(background, /inspector-background-opaque-description/);
  assert.match(background, /serializeBackgroundLonghands/);
  assert.match(gradient, /inspector-background-gradient-css-source/);
  assert.match(gradient, /parseCssGradient/);
  assert.match(shadows, /boxStructured/);
  assert.match(shadows, /textStructured/);
  assert.match(shadows, /t\("inspector-shadow-complex"\)/);
});

test("background editing is Rust-first, layered and committed as one property set", () => {
  const rustModel = source("src-tauri/src/css/background.rs");
  const viewport = source("src-tauri/src/css/viewport.rs");
  const inspector = source("src/lib/components/inspector/CssInspectorCoordinator.svelte");
  const queue = source("src/lib/inspector/css-inspector-mutation-queue.ts");
  const background = source("src/lib/components/inspector/sections/BackgroundSection.svelte");
  const typography = source("src/lib/components/inspector/sections/TypographySection.svelte");
  const legacyEditor = new URL("../src/lib/components/inspector/sections/ColorsSection.svelte", import.meta.url);

  assert.match(rustModel, /pub struct CssBackground/);
  assert.match(rustModel, /pub struct CssBackgroundLayer/);
  assert.match(rustModel, /split_top_level_commas/);
  assert.match(rustModel, /pub fn to_longhands/);
  assert.match(viewport, /pub background: CssBackground/);
  assert.match(queue, /private draftProperties\(/);
  assert.match(queue, /this\.stage\(mutation, property, value/);
  assert.match(background, /BACKGROUND_LONGHAND_PROPERTIES/);
  assert.match(background, /edit\.commitMany\(properties\)/);
  assert.match(background, /moveLayer/);
  assert.match(background, /duplicateLayer/);
  assert.match(typography, /edit\.continuous\("color"\)/);
  assert.equal(existsSync(legacyEditor), false);
});

test("CSS coordinator is only the lazy Svelte adapter for focused domain owners", () => {
  const coordinator = source("src/lib/components/inspector/CssInspectorCoordinator.svelte");
  const script = coordinator.slice(
    coordinator.indexOf("<script"),
    coordinator.indexOf("</script>"),
  );
  const state = source("src/lib/inspector/css-inspector-state.svelte.ts");
  const reader = source("src/lib/inspector/css-inspector-reader.ts");
  const queue = source("src/lib/inspector/css-inspector-mutation-queue.ts");

  assert.ok(script.split("\n").length <= 300);
  assert.match(coordinator, /new CssInspectorState\(\)/);
  assert.match(coordinator, /new CssInspectorReader\(inspectorState/);
  assert.match(coordinator, /new CssInspectorMutationQueue\(/);
  assert.doesNotMatch(coordinator, /new Map|queueMicrotask|resolveCssInspectorContext|setCssRuleAtViewport/);
  assert.match(state, /class CssInspectorState/);
  assert.match(reader, /class CssInspectorReader/);
  assert.match(queue, /class CssInspectorMutationQueue/);
});
