import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

function source(path) {
  return readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
}

test("catalogul semantic al tokenilor este deținut de Rust și legat de ProjectWorkspace", () => {
  const command = source("src-tauri/src/commands/design_system.rs");
  const registry = source("src-tauri/src/tauri_command_registry.rs");
  const kernel = source("src-tauri/src/kernel/design_system/tokens.rs");
  const io = source("src/lib/css/io.ts");

  assert.match(
    command,
    /read_design_token_catalog[\s\S]*with_bound_css_file_buffer_revision[\s\S]*build_design_token_catalog/,
  );
  assert.match(registry, /read_design_token_catalog/);
  assert.match(kernel, /DESIGN_TOKEN_CATALOG_SCHEMA_VERSION/);
  assert.match(kernel, /entry\.current_text\(\)/);
  assert.match(kernel, /workspace_revision/);
  assert.match(kernel, /resolved_value/);
  assert.match(kernel, /Dependență circulară între tokeni/);
  assert.doesNotMatch(kernel, /std::fs::(?:read|write)/);
  assert.match(io, /readDesignTokenCatalog[\s\S]*"read_design_token_catalog"/);
  assert.equal(
    existsSync(
      new URL(
        "../src-tauri/permissions/autogenerated/read_design_token_catalog.toml",
        import.meta.url,
      ),
    ),
    true,
  );
});

test("frontendul prezintă catalogul Rust fără clasificarea SCSS legacy", () => {
  const workspace = source("src/lib/components/creation/design-system/DesignTokensWorkspace.svelte");
  const catalog = source("src/lib/components/creation/DesignTokenCatalog.svelte");
  const state = source("src/lib/components/creation/design-system/catalog-state.svelte.ts");
  const shell = source("src/lib/components/creation/design-system/ResourceWorkspaceShell.svelte");

  assert.match(state, /readDesignTokenCatalog/);
  assert.match(workspace, /<DesignTokenCatalog/);
  assert.match(workspace, /selectedToken\.rawValue/);
  assert.match(workspace, /selectedToken\.resolvedValue/);
  assert.doesNotMatch(workspace, /function variableCategory|type TokenCategory/);
  assert.match(workspace, /tokens=\{visibleTokens\}/);
  assert.doesNotMatch(catalog, /normalizedQuery|\bquery\b|\bcategory\b/);

  assert.match(catalog, /class="token-sections"/);
  assert.match(catalog, /class="token-grid"/);
  assert.match(catalog, /token\.visualKind === "color"/);
  assert.match(catalog, /token\.visualKind === "spacing"/);
  assert.match(catalog, /token\.visualKind === "radius"/);
  assert.match(catalog, /t\("design-token-title-color"\)/);
  assert.match(catalog, /t\("design-token-title-typography"\)/);
  assert.doesNotMatch(catalog, /tokeni confirmați și rezolvați de catalogul Rust/);
  assert.doesNotMatch(catalog, /#7c3aed/);
  assert.match(
    catalog,
    /\.radius-sample\s*\{[\s\S]*border:\s*2px solid var\(--wb-accent\)/,
  );
  assert.doesNotMatch(catalog, /IconCode|source-action|openSource/);
  assert.match(
    catalog,
    /\.token-sections\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)/,
  );
  assert.match(
    catalog,
    /\.token-section\s*\{[\s\S]*border-bottom:\s*1px solid var\(--wb-border-subtle\)/,
  );
  assert.doesNotMatch(catalog, /\.token-section\s*\{[^}]*border:\s*1px/);
  assert.doesNotMatch(catalog, /\.section-icon\.(?:color|typography|spacing|radius)/);
  assert.match(
    shell,
    /\.workspace-body\s*\{[\s\S]*grid-template-columns:\s*minmax\(340px,\s*1fr\)\s*minmax\(290px,\s*\.58fr\)/,
  );
  assert.doesNotMatch(workspace, /tokens-active/);
});
