import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

function source(path) {
  return readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
}

test("Stiluri is the first Design tab and has no create state", () => {
  const workspace = source("src/lib/components/creation/DesignSystemWorkspace.svelte");
  const themeStyles = source("src/lib/components/creation/ThemeStylesWorkspace.svelte");

  assert.match(
    workspace,
    /const designViews[\s\S]*\{ id: "global-styles", label: "Stiluri" \}[\s\S]*\{ id: "tokens"/,
  );
  assert.match(workspace, /\{#if activeView !== "global-styles"\}[\s\S]*Adaugă/);
  assert.match(workspace, /<ThemeStylesWorkspace/);
  assert.match(themeStyles, /type DetailMode = "info" \| "edit"/);
  assert.doesNotMatch(themeStyles, /"create"|window\.(?:prompt|confirm)/);
});

test("theme style draft previews are read-only and Apply is one Rust workspace mutation", () => {
  const component = source("src/lib/components/creation/ThemeStylesWorkspace.svelte");
  const commands = source("src-tauri/src/commands/design_system.rs");
  const cssCommands = source("src-tauri/src/commands/css.rs");
  const io = source("src/lib/project/io.ts");

  assert.match(component, /previewThemeStyleDraft/);
  assert.match(component, /registerEditFlushHandler\(\s*"theme-styles-workspace"/);
  assert.match(component, /applyThemeStyleDraft/);
  assert.match(component, /projectCommittedInspectorCssMutation\(receipt\.authority, null\)/);
  assert.match(commands, /preview_theme_style_draft[\s\S]*with_bound_css_file_buffer_revision/);
  assert.match(commands, /apply_theme_style_draft[\s\S]*execute_css_workspace_mutation_with_metadata/);
  assert.match(commands, /"design_system\.theme_styles"/);
  assert.match(commands, /expected_workspace_revision/);
  assert.match(cssCommands, /theme_style_stale_workspace/);
  assert.match(cssCommands, /coalesce_prefix: Option<&str>/);
  assert.match(io, /"preview_theme_style_draft"/);
  assert.match(io, /"apply_theme_style_draft"/);
  assert.doesNotMatch(component, /!important/);
});

test("Rust owns the semantic registry, inheritance and protected property allowlists", () => {
  const registry = source("src-tauri/src/kernel/design_system/theme_styles.rs");
  const rules = source("src-tauri/src/css/rules/selector.rs");

  for (const category of [
    "General",
    "Tipografie",
    "Linkuri",
    "Media",
    "Liste",
    "Citate și cod",
    "Tabele",
    "Formulare",
    "Elemente auxiliare",
  ]) {
    assert.ok(registry.includes(`"${category}"`), category);
  }
  assert.match(registry, /theme_style_property_protected/);
  assert.match(registry, /inherited_from/);
  assert.match(registry, /resolve_scss_tokens/);
  assert.match(registry, /theme_style_source_(?:missing|ambiguous)/);
  assert.match(rules, /locate_exact_rule_block/);
  assert.doesNotMatch(registry, /std::fs::(?:read|write)/);
});

test("all theme style commands have explicit Tauri permissions", () => {
  for (const command of [
    "read_theme_style_catalog",
    "preview_theme_style_draft",
    "apply_theme_style_draft",
  ]) {
    assert.equal(
      existsSync(new URL(`../src-tauri/permissions/autogenerated/${command}.toml`, import.meta.url)),
      true,
      command,
    );
  }
  const registry = source("src-tauri/src/tauri_command_registry.rs");
  assert.match(registry, /read_theme_style_catalog/);
  assert.match(registry, /preview_theme_style_draft/);
  assert.match(registry, /apply_theme_style_draft/);
});
