import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { test } from "node:test";

const repoRoot = resolve(new URL("..", import.meta.url).pathname);
const source = (path) => readFileSync(resolve(repoRoot, path), "utf8");

test("Zola runtime has no executable, resolver, sidecar or exposed path", () => {
  assert.equal(existsSync(resolve(repoRoot, "src-tauri/binaries/zola")), false);
  assert.equal(existsSync(resolve(repoRoot, "src-tauri/binaries/zola.sha256")), false);
  assert.equal(existsSync(resolve(repoRoot, "src-tauri/src/preview/zola.rs")), false);
  assert.equal(
    existsSync(resolve(repoRoot, "src-tauri/permissions/autogenerated/get_zola_binary_path.toml")),
    false,
  );

  const runtimeCorpus = [
    source("src-tauri/src/lib.rs"),
    source("src-tauri/src/state.rs"),
    source("src-tauri/src/commands/project.rs"),
    source("src-tauri/src/commands/deploy.rs"),
    source("src-tauri/tauri.conf.json"),
    source("src/lib/project/io.ts"),
    source("src/lib/state/app.svelte.ts"),
    source("src/lib/state/terminal-quick-task-controller.ts"),
  ].join("\n");
  assert.doesNotMatch(
    runtimeCorpus,
    /get_zola_binary_path|zola_binary_path|binaries\/zola|\/usr\/bin\/zola|useBundledZola/,
  );
  assert.doesNotMatch(runtimeCorpus, /Command::new\([^)]*[Zz]ola/);
});

test("official embedded crates are pinned to the audited Zola 0.22.1 revision", () => {
  const cargo = source("src-tauri/Cargo.toml");
  const revision = "29540e9897dbe8aca388b13f7bdf615985f6ca2c";
  assert.match(
    cargo,
    new RegExp(`zola-site = \\{ package = "site", git = "https://github\\.com/getzola/zola\\.git", rev = "${revision}" \\}`),
  );
  assert.match(
    cargo,
    new RegExp(`zola-utils = \\{ package = "utils", git = "https://github\\.com/getzola/zola\\.git", rev = "${revision}" \\}`),
  );
});

test("init, validation, build and quick tasks use only embedded engine contracts", () => {
  const initializer = source("src-tauri/src/project/init.rs").split("#[cfg(test)]")[0];
  const engine = source("src-tauri/src/zola_engine.rs");
  const build = source("src-tauri/src/deploy/zola.rs");
  const buildRuntime = build
    .split("#[cfg(test)]\nmod tests")[0]
    .replace("#[cfg(test)]\nuse std::fs;", "");
  const writeCapability = source("src-tauri/src/kernel/write_authority/capability.rs");
  const preview = source("src-tauri/src/preview/engine.rs").split("#[cfg(test)]")[0];
  const terminal = source("src/lib/terminal/runtime.ts");
  const terminalController = source("src/lib/state/terminal-quick-task-controller.ts");

  assert.match(initializer, /apply_starter/);
  assert.match(initializer, /ProjectBootstrapLease/);
  assert.doesNotMatch(initializer, /std::process|Command::new|Stdio/);
  assert.match(engine, /static ZOLA_ENGINE_AUTHORITY: Mutex/);
  assert.match(build, /Site::new/);
  assert.match(build, /enable_check_mode/);
  assert.match(build, /ZolaArtifactPublicationLease/);
  assert.doesNotMatch(buildRuntime, /fs::rename|fs::remove_dir_all|renameat_with/);
  assert.match(writeCapability, /publish_rebuildable_directory/);
  assert.match(writeCapability, /RenameFlags::EXCHANGE/);
  assert.match(build, /process_images/);
  assert.match(preview, /with_zola_engine/);
  assert.doesNotMatch(preview, /std::process|Command::new/);
  assert.match(terminal, /kind: "embedded-check"/);
  assert.match(terminal, /kind: "embedded-build"/);
  assert.match(terminal, /kind: "internal-preview"/);
  assert.doesNotMatch(terminalController, /writeCommand\([^,]+,\s*["'`](?:zola|check|build|serve)/);
});
