use super::types::PageJsConfig;

pub fn generate_motion_js(config: &PageJsConfig) -> String {
    if !config.has_motion_items() {
        return String::new();
    }

    let payload = serde_json::json!({
        "version": config.version.unwrap_or(1),
        "motion": config.motion,
    });
    let payload_json = serde_json::to_string(&payload).unwrap_or_else(|_| "{}".to_string());

    format!(
        r#"    /* === MOTION STUDIO === */
    (function(){{
      var anime=window.anime||{{}};
      var payload={payload_json};
      var motion=payload.motion||{{items:[]}};
      var registry=window.__panaMotion=window.__panaMotion||{{items:{{}},errors:[]}};
      var runningTimelines={{}};
      var animate=anime.animate||function(){{return null;}};
      var createTimeline=anime.createTimeline||function(){{return null;}};
      var createTimer=anime.createTimer||function(){{return null;}};
      var createAnimatable=anime.createAnimatable||function(){{return null;}};
      var createDraggable=anime.createDraggable||function(){{return null;}};
      var createLayout=anime.createLayout||function(){{return null;}};
      var createScope=anime.createScope||function(){{return null;}};
      var onScroll=anime.onScroll||function(){{return null;}};
      var stagger=anime.stagger||function(v){{return v||0;}};
      var waapi=anime.waapi||null;
      var engine=anime.engine||null;
      function warn(item,error){{registry.errors.push({{id:item&&item.id,type:item&&item.type,message:error&&error.message?error.message:String(error)}});if(console&&console.warn)console.warn('[Pana Motion]',item&&item.type,item&&item.id,error);}}
      function esc(value){{return String(value||'').replace(/\\/g,'\\\\').replace(/"/g,'\\"');}}
      function hasText(value){{return typeof value==='string'&&value.trim().length>0;}}
      function runExpression(expression,args,fallback){{if(!expression||!expression.enabled||!hasText(expression.code))return fallback;try{{var fn=(0,eval)('('+expression.code+')');return typeof fn==='function'?fn.apply(null,args||[]):fn;}}catch(error){{warn({{id:expression.label,type:'expression'}},error);return fallback;}}}}
      function expressionCallback(expression){{if(!expression||!expression.enabled||!hasText(expression.code))return undefined;return function(self){{return runExpression(expression,[self,anime,anime.utils||anime],undefined);}};}}
      function readTarget(item){{var target=item.target||{{}};if(target.mode==='expression')return runExpression({{enabled:true,label:'target',code:target.expression}},[item,anime],[]);if(target.mode==='dataAnim'&&hasText(target.dataAnim))return '[data-anim="'+esc(target.dataAnim)+'"]';if(hasText(target.selector))return target.selector;if(hasText(target.dataAnim))return '[data-anim="'+esc(target.dataAnim)+'"]';return [];}}
      function parseMaybeNumber(value){{if(typeof value!=='string')return value;if(value.trim()==='')return value;var n=Number(value);return Number.isFinite(n)&&String(n)===value.trim()?n:value;}}
      function parsePosition(value,fallback){{if(typeof value==='number')return Math.max(0,Math.round(value));var text=String(value||'').trim();if(!text)return fallback||0;var seconds=text.match(/^(-?\d+(?:\.\d+)?)s$/);if(seconds)return Math.max(0,Math.round(Number(seconds[1])*1000));var ms=text.match(/^(-?\d+(?:\.\d+)?)ms$/);if(ms)return Math.max(0,Math.round(Number(ms[1])));var raw=Number(text);return Number.isFinite(raw)?Math.max(0,Math.round(raw)):fallback||0;}}
      function parseArgs(text){{if(!hasText(text))return[];try{{var result=(0,eval)('['+text+']');return Array.isArray(result)?result:[];}}catch(error){{return String(text).split(',').map(function(part){{return parseMaybeNumber(part.trim());}});}}}}
      function parseInlineObject(text){{if(!hasText(text))return{{}};var trimmed=String(text).trim();try{{if(trimmed.charAt(0)==='{{')return (0,eval)('('+trimmed+')');}}catch(error){{}}var result={{}};trimmed.split(';').forEach(function(entry){{var index=entry.indexOf(':');if(index===-1)return;var key=entry.slice(0,index).trim();var value=entry.slice(index+1).trim();if(key)result[key]=parseMaybeNumber(value);}});return result;}}
      function compactObject(object){{var result={{}};Object.keys(object||{{}}).forEach(function(key){{var value=object[key];if(value!==undefined&&value!==null&&value!=='')result[key]=value;}});return result;}}
      function resolveUtil(name){{return anime.utils&&anime.utils[name]||anime[name];}}
      function resolveEasingFunction(name){{return anime[name]||anime.easings&&anime.easings[name];}}
      function easingValue(item){{if(!item)return'';var value=item.value||'';if(item.mode==='custom')return runExpression(item.advanced&&item.advanced[0],[anime,anime.utils||anime],value);if(item.mode==='builtIn')return value;var args=parseArgs(value);if(item.mode==='cubicBezier'){{var cubicBezier=resolveEasingFunction('cubicBezier');return cubicBezier?cubicBezier.apply(null,args):value;}}if(item.mode==='linear'){{var linear=resolveEasingFunction('linear');return linear?linear.apply(null,args):value;}}if(item.mode==='steps'){{var steps=resolveEasingFunction('steps');return steps?steps.apply(null,args):value;}}if(item.mode==='irregular'){{var irregular=resolveEasingFunction('irregular');return irregular?irregular.apply(null,args):value;}}if(item.mode==='spring'){{var spring=resolveEasingFunction('spring')||resolveEasingFunction('createSpring');return spring?spring.apply(null,args):value;}}return value;}}
      function withUnit(value,unit){{if(!hasText(unit))return parseMaybeNumber(value);if(typeof value==='number'||/^-?\d+(\.\d+)?$/.test(String(value).trim()))return String(value).trim()+unit;return value;}}
      function relativeWithUnit(value,unit){{var text=String(value||'').trim();if(!hasText(unit))return text;if(/^[+-]=\d+(\.\d+)?$/.test(text))return text+unit;return withUnit(text,unit);}}
      function cssVarValue(value){{var text=String(value||'').trim();if(!text)return text;if(text.indexOf('var(')===0)return text;if(text.indexOf('--')===0)return 'var('+text+')';return text;}}
      function randomValue(value){{var parts=String(value.value||'0,1').split(/[,\s]+/).map(Number).filter(Number.isFinite);var min=parts[0]||0,max=parts.length>1?parts[1]:1;var random=anime.random?anime.random(min,max):min+Math.random()*(max-min);return hasText(value.unit)?String(random)+value.unit:random;}}
      function motionValue(value){{value=value||{{}};if(value.mode==='expression'||value.mode==='function')return runExpression({{enabled:true,label:'value',code:value.expression}},[anime],undefined);if(value.mode==='random')return randomValue(value);if(value.mode==='relative')return relativeWithUnit(value.value,value.unit);if(value.mode==='cssVariable')return cssVarValue(value.value);if(value.mode==='literal'||value.mode==='color')return withUnit(value.value,value.unit);if(value.mode==='fromTo')return [withUnit(value.from,value.unit),withUnit(value.to,value.unit)];return hasText(value.to)?[withUnit(value.from,value.unit),withUnit(value.to,value.unit)]:withUnit(value.value,value.unit);}}
      function propertyValue(prop){{var value=prop.value||{{}};var tween=prop.tween||{{}};var base=motionValue(value);var hasModifier=prop.modifier&&prop.modifier.enabled&&hasText(prop.modifier.code);var hasComposition=hasText(prop.composition)&&prop.composition!=='replace';var hasTween=(Number.isFinite(+tween.delay)&&+tween.delay>0)||(Number.isFinite(+tween.duration)&&+tween.duration>0)||hasText(tween.ease);if(!hasModifier&&!hasComposition&&!hasTween)return base;var object={{}};if(value.mode==='fromTo'){{if(hasText(value.from))object.from=withUnit(value.from,value.unit);if(hasText(value.to))object.to=withUnit(value.to,value.unit);}}else object.to=base;if(hasModifier)object.modifier=runExpression(prop.modifier,[anime],undefined);if(hasComposition)object.composition=prop.composition;if(Number.isFinite(+tween.delay)&&+tween.delay>0)object.delay=+tween.delay;if(Number.isFinite(+tween.duration)&&+tween.duration>0)object.duration=+tween.duration;if(hasText(tween.ease))object.ease=tween.ease;return object;}}
      function assignProps(params,props){{(props||[]).forEach(function(prop){{if(!prop||!hasText(prop.property))return;params[prop.property]=propertyValue(prop);}});return params;}}
      function applyPlayback(params,playback){{playback=playback||{{}};if(Number.isFinite(+playback.delay))params.delay=+playback.delay;if(Number.isFinite(+playback.duration))params.duration=+playback.duration;if(Number.isFinite(+playback.loopDelay))params.loopDelay=+playback.loopDelay;if(playback.loop===-1)params.loop=true;else if(Number.isFinite(+playback.loop)&&+playback.loop>0)params.loop=+playback.loop;if(playback.alternate)params.alternate=true;if(playback.reversed)params.reversed=true;if(playback.autoplay===false)params.autoplay=false;if(Number.isFinite(+playback.frameRate)&&+playback.frameRate>0)params.frameRate=+playback.frameRate;if(Number.isFinite(+playback.playbackRate)&&+playback.playbackRate!==1)params.playbackRate=+playback.playbackRate;if(hasText(playback.playbackEase)){{params.ease=playback.playbackEase;params.playbackEase=playback.playbackEase;}}if(playback.persist)params.persist=true;return params;}}
      function callbackParamName(name){{name=String(name||'');if(/^on[A-Z]/.test(name))return name;return 'on'+name.charAt(0).toUpperCase()+name.slice(1);}}
      function applyCallbacks(params,callbacks){{callbacks=callbacks||{{}};Object.keys(callbacks).forEach(function(name){{var callback=expressionCallback(callbacks[name]);if(!callback)return;params[callbackParamName(name)]=callback;}});return params;}}
      function applyAdvanced(params,item){{(item.advanced||[]).forEach(function(expression){{runExpression(expression,[params,item,anime],undefined);}});return params;}}
      function staggerDelay(staggerConfig){{if(!staggerConfig||!staggerConfig.enabled)return undefined;var options={{}};if(Number.isFinite(+staggerConfig.start))options.start=+staggerConfig.start;if(hasText(staggerConfig.from))options.from=staggerConfig.from;if(staggerConfig.reversed)options.reversed=true;if(hasText(staggerConfig.ease))options.ease=staggerConfig.ease;if(hasText(staggerConfig.grid)){{var grid=staggerConfig.grid.split(/[,\sx]+/).map(Number).filter(Number.isFinite);if(grid.length>=2)options.grid=[grid[0],grid[1]];}}if(hasText(staggerConfig.axis))options.axis=staggerConfig.axis;if(Number.isFinite(+staggerConfig.total)&&+staggerConfig.total>0)options.total=+staggerConfig.total;if(staggerConfig.modifier&&staggerConfig.modifier.enabled)options.modifier=runExpression(staggerConfig.modifier,[anime],undefined);return stagger(+staggerConfig.each||0,options);}}
      function nodeList(target){{if(!target)return[];if(typeof target==='string')return Array.prototype.slice.call(document.querySelectorAll(target));if(target.nodeType)return[target];if(typeof target.length==='number')return Array.prototype.slice.call(target);return[target];}}
      function splitTextSpans(el,effect){{if(!hasText(effect)||effect==='none')return;if(el.__panaMotionSplit===effect)return;var text=el.textContent||'';if(effect==='words')el.innerHTML=text.trim().split(/\s+/).map(function(w){{return '<span style="display:inline-block">'+w+'</span>';}}).join('<span style="display:inline-block">&nbsp;</span>');else el.innerHTML=text.split('').map(function(c){{return '<span style="display:inline-block">'+(c===' '?'&nbsp;':c)+'</span>';}}).join('');el.__panaMotionSplit=effect;}}
      function scopedSelector(selector){{selector=selector||'';var trimmed=selector.trim();if(!trimmed)return'';if(trimmed.charAt(0)==='>'||trimmed.charAt(0)==='+'||trimmed.charAt(0)==='~')return ':scope '+trimmed;return trimmed;}}
      function animationTargets(item,baseEl){{var base=baseEl?[baseEl]:nodeList(readTarget(item));if(!hasText(item.targetSelector)&&!hasText(item.textEffect))return baseEl?baseEl:readTarget(item);var result=[];base.forEach(function(el){{splitTextSpans(el,item.textEffect);if(hasText(item.textEffect))result=result.concat(Array.prototype.slice.call(el.querySelectorAll('span')));else if(hasText(item.targetSelector))result=result.concat(Array.prototype.slice.call(el.querySelectorAll(scopedSelector(item.targetSelector))));else result.push(el);}});return result;}}
      function isPercentAt(value){{return /^\d+(\.\d+)?%$/.test(String(value||'').trim());}}
      function keyframeParams(item){{var frames=[];var percentFrames={{}};var hasPercent=false;var hasOther=false;(item.keyframes||[]).forEach(function(frame){{var params=assignProps({{}},frame.properties);if(Number.isFinite(+frame.duration))params.duration=+frame.duration;if(hasText(frame.ease))params.ease=frame.ease;(frame.advanced||[]).forEach(function(expression){{runExpression(expression,[params,frame,item,anime],undefined);}});if(isPercentAt(frame.at)){{hasPercent=true;percentFrames[String(frame.at).trim()]=params;}}else{{hasOther=true;if(hasText(frame.at))params.at=frame.at;frames.push(params);}}}});return hasPercent&&!hasOther?percentFrames:frames;}}
      function hasKeyframes(frames){{return Array.isArray(frames)?frames.length>0:Boolean(frames&&Object.keys(frames).length);}}
      function buildAnimationParams(item){{var params=applyPlayback(assignProps({{}},item.properties),item.playback);applyCallbacks(params,item.callbacks);applyAdvanced(params,item);var staggerValue=staggerDelay(item.stagger);if(staggerValue!==undefined){{var use=item.stagger&&hasText(item.stagger.use)?item.stagger.use:'delay';params[use]=staggerValue;}}var frames=keyframeParams(item);if(hasKeyframes(frames))params.keyframes=frames;return params;}}
      function runAnimation(item){{var trigger=item.trigger||'load';if(trigger==='scroll'&&item.scrollScrub){{var params=buildAnimationParams(item);params.autoplay=onScroll({{target:readTarget(item),sync:true}});registry.items[item.id]=animate(animationTargets(item),params);return;}}if(trigger==='scroll'){{var observer=new IntersectionObserver(function(entries){{entries.forEach(function(entry){{if(!entry.isIntersecting)return;animate(animationTargets(item,entry.target),buildAnimationParams(item));if(!item.scrollRepeat)observer.unobserve(entry.target);}});}},{{threshold:0.15}});nodeList(readTarget(item)).forEach(function(el){{observer.observe(el);}});registry.items[item.id]=observer;return;}}if(trigger==='click'||trigger==='hover'){{nodeList(readTarget(item)).forEach(function(el){{var run=function(){{animate(animationTargets(item,el),buildAnimationParams(item));}};if(trigger==='click')el.addEventListener('click',run);else el.addEventListener('mouseenter',run);}});registry.items[item.id]=true;return;}}registry.items[item.id]=animate(animationTargets(item),buildAnimationParams(item));}}
      function runTimer(item){{var params=applyPlayback({{}},item.playback);applyCallbacks(params,item.callbacks);applyAdvanced(params,item);registry.items[item.id]=createTimer(params);}}
      function runTimeline(item){{if(runningTimelines[item.id]){{warn(item,new Error('Timeline circular sync'));return;}}runningTimelines[item.id]=true;var params=applyPlayback({{}},item.playback);if(Number.isFinite(+item.duration)&&+item.duration>0)params.duration=+item.duration;applyAdvanced(params,item);var timeline=createTimeline(params);if(!timeline){{delete runningTimelines[item.id];return;}}registry.items[item.id]=timeline;var byId={{}};(motion.items||[]).forEach(function(entry){{if(entry&&entry.id)byId[entry.id]=entry;}});(item.labels||[]).forEach(function(label){{if(timeline.label)timeline.label(label.name,label.position||undefined);}});(item.steps||[]).forEach(function(step){{var position=hasText(step.position)?step.position:parsePosition(step.position,0);if(step.type==='label'&&timeline.label)timeline.label(step.label,position);else if(step.type==='callback'&&timeline.call)timeline.call(expressionCallback(step.callback)||function(){{}},position);else if(step.type==='timer'&&timeline.add)timeline.add({{duration:+step.duration||0}},position);else if(step.type==='sync'&&timeline.sync){{var syncTarget=byId[step.targetItemId];if(!syncTarget||syncTarget.id===item.id){{if(syncTarget&&syncTarget.id===item.id)warn(item,new Error('Timeline cannot sync itself'));return;}}if(syncTarget.type==='timeline'&&runningTimelines[syncTarget.id]){{warn(item,new Error('Timeline circular sync'));return;}}if(syncTarget.type==='timeline'&&!registry.items[syncTarget.id])runTimeline(syncTarget);var syncInstance=registry.items[step.targetItemId];if(syncInstance&&syncInstance!==timeline)timeline.sync(syncInstance,position);}}else if(step.type==='animation'&&timeline.add){{var target=byId[step.targetItemId];if(!target||target.type!=='animation')return;var animationParams=buildAnimationParams(target);if(Number.isFinite(+step.duration)&&+step.duration>0)animationParams.duration=+step.duration;timeline.add(animationTargets(target),animationParams,position);}}else if(step.type==='set'&&timeline.set){{var setTarget=byId[step.targetItemId];if(!setTarget)return;timeline.set(readTarget(setTarget),assignProps({{}},setTarget.properties||[]),position);}}}});delete runningTimelines[item.id];}}
      function animatableParams(item){{var params={{}};if(hasText(item.ease))params.ease=item.ease;(item.properties||[]).forEach(function(prop){{if(!prop||!hasText(prop.property))return;var tween=prop.tween||{{}};var setting={{}};var duration=Number.isFinite(+tween.duration)&&+tween.duration>0?+tween.duration:+item.duration;if(Number.isFinite(duration)&&duration>0)setting.duration=duration;var unit=prop.value&&hasText(prop.value.unit)?prop.value.unit:item.unit;if(hasText(unit))setting.unit=unit;if(hasText(tween.ease))setting.ease=tween.ease;params[prop.property]=Object.keys(setting).length?setting:duration||500;}});return params;}}
      function animatableSet(instance,item,x,y){{(item.properties||[]).forEach(function(prop){{if(!prop||!hasText(prop.property)||typeof instance[prop.property]!=='function')return;var name=prop.property.toLowerCase();var value=name.indexOf('y')!==-1?y:x;instance[prop.property](value,+item.duration||undefined,item.ease||undefined);}});}}
      function runAnimatable(item){{var target=readTarget(item);var instance=createAnimatable(target,animatableParams(item));applyAdvanced(instance,item);registry.items[item.id]=instance;if(item.mode==='getters')return;if(item.liveSource==='expression'){{runExpression(item.setterExpression,[instance,target,anime,anime.utils||anime],undefined);return;}}if(item.liveSource==='pointer'){{var nodes=nodeList(target);var pointer=function(event){{var el=nodes[0];if(!el)return;var rect=el.getBoundingClientRect();animatableSet(instance,item,event.clientX-rect.left-rect.width/2,event.clientY-rect.top-rect.height/2);}};window.addEventListener('pointermove',pointer,{{passive:true}});return;}}if(item.liveSource==='scroll'){{var scroll=function(){{animatableSet(instance,item,window.scrollX||window.pageXOffset||0,window.scrollY||window.pageYOffset||0);}};window.addEventListener('scroll',scroll,{{passive:true}});scroll();}}}}
      function parseAxisValue(value){{if(!hasText(value))return undefined;var text=String(value).trim();if(text.charAt(0)==='['||text.charAt(0)==='{{')return runExpression({{enabled:true,label:'axis value',code:'function(){{return '+text+';}}'}},[anime],parseMaybeNumber(text));if(text.indexOf(',')!==-1)return text.split(',').map(function(part){{return parseMaybeNumber(part.trim());}});return parseMaybeNumber(text);}}
      function draggableAxis(enabled,snap,mapTo){{if(!enabled)return false;var axis={{}};var snapValue=parseAxisValue(snap);if(snapValue!==undefined)axis.snap=snapValue;if(hasText(mapTo))axis.mapTo=mapTo;return Object.keys(axis).length?axis:true;}}
      function runDraggable(item){{var params={{}};params.x=draggableAxis(item.axes!=='y',item.snapX||item.snap,item.mapTo);params.y=draggableAxis(item.axes!=='x',item.snapY||item.snap,item.mapTo);if(hasText(item.container))params.container=item.container;if(hasText(item.trigger))params.trigger=item.trigger;if(item.modifier&&item.modifier.enabled)params.modifier=runExpression(item.modifier,[anime],undefined);if(Number.isFinite(+item.containerPadding)&&+item.containerPadding>0)params.containerPadding=+item.containerPadding;if(Number.isFinite(+item.friction))params.containerFriction=+item.friction;if(Number.isFinite(+item.releaseContainerFriction)&&+item.releaseContainerFriction>0)params.releaseContainerFriction=+item.releaseContainerFriction;if(Number.isFinite(+item.velocity))params.velocityMultiplier=+item.velocity;if(Number.isFinite(+item.minVelocity)&&+item.minVelocity>0)params.minVelocity=+item.minVelocity;if(Number.isFinite(+item.maxVelocity)&&+item.maxVelocity>0)params.maxVelocity=+item.maxVelocity;if(hasText(item.releaseEase))params.releaseEase=item.releaseEase;if(Number.isFinite(+item.dragSpeed)&&+item.dragSpeed>0)params.dragSpeed=+item.dragSpeed;if(Number.isFinite(+item.dragThreshold)&&+item.dragThreshold>0)params.dragThreshold=+item.dragThreshold;if(Number.isFinite(+item.scrollThreshold)&&+item.scrollThreshold>0)params.scrollThreshold=+item.scrollThreshold;if(Number.isFinite(+item.scrollSpeed)&&+item.scrollSpeed>0)params.scrollSpeed=+item.scrollSpeed;if(typeof item.cursor==='boolean')params.cursor=item.cursor;if(item.release){{if(Number.isFinite(+item.release.mass))params.releaseMass=+item.release.mass;if(Number.isFinite(+item.release.stiffness))params.releaseStiffness=+item.release.stiffness;if(Number.isFinite(+item.release.damping))params.releaseDamping=+item.release.damping;}}applyCallbacks(params,item.callbacks);applyAdvanced(params,item);registry.items[item.id]=createDraggable(readTarget(item),params);}}
      function layoutProperties(item){{if(hasText(item.properties))return item.properties.split(',').map(function(part){{return part.trim();}}).filter(Boolean);var props=[];if(item.includeDisplay)props.push('display');if(item.includeGrid)props=props.concat(['gridTemplateColumns','gridTemplateRows','gap']);if(item.includeFlex)props=props.concat(['flexBasis','flexGrow','flexShrink']);if(item.includeOrder)props.push('order');return props;}}
      function runLayout(item){{var params=applyPlayback({{}},item.playback);if(hasText(item.children))params.children=item.children;var props=layoutProperties(item);if(props.length)params.properties=props;if(item.enterExit&&hasText(item.enterFrom))params.enterFrom=parseInlineObject(item.enterFrom);if(item.enterExit&&hasText(item.leaveTo))params.leaveTo=parseInlineObject(item.leaveTo);if(item.swapParent&&hasText(item.swapAt))params.swapAt=parseMaybeNumber(item.swapAt);applyCallbacks(params,item.callbacks);applyAdvanced(params,item);var layout=createLayout(readTarget(item),params);registry.items[item.id]=layout;if(!layout)return;if(item.mode==='record'&&layout.record)layout.record();else if(item.mode==='animate'&&layout.animate)layout.animate();else if(item.mode==='update'&&layout.update)layout.update(function(){{}});else if(item.mode==='revert'&&layout.revert)layout.revert();}}
      function scopeRoot(root){{if(!hasText(root))return document;try{{return document.querySelector(root)||root;}}catch(error){{return root;}}}}
      function runScope(item){{if(item.reducedMotion==='disable'&&window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;var params={{root:scopeRoot(item.root||item.target&&item.target.selector),defaults:item.defaults||{{}},mediaQueries:{{}}}};(item.mediaQueries||[]).forEach(function(query){{if(query.enabled!==false&&hasText(query.query))params.mediaQueries[query.id||query.query]=query.query;}});applyAdvanced(params,item);var scope=createScope(params);if(scope&&item.keepTime&&scope.keepTime)scope.keepTime();registry.items[item.id]=scope;}}
      function applyScrollSync(params,item){{var mode=item.syncMode||'methods';if(mode==='progress'){{params.sync=true;return;}}if(mode==='smooth'){{var smooth=Number(item.smooth);params.sync=Number.isFinite(smooth)&&smooth>0?smooth:true;return;}}if(mode==='eased'){{params.sync=hasText(item.syncEase)?item.syncEase:true;return;}}if(hasText(item.syncMethods)){{params.sync=item.syncMethods;return;}}if(hasText(item.sync))params.sync=item.sync==='progress'?true:item.sync;}}
      function runScroll(item){{var params={{target:readTarget(item)}};if(hasText(item.container))params.container=item.container;if(hasText(item.axis))params.axis=item.axis;if(typeof item.repeat==='boolean')params.repeat=item.repeat;if(item.debug)params.debug=true;var enter=hasText(item.enter)?item.enter:item.threshold;var leave=hasText(item.leave)?item.leave:'';if(hasText(enter))params.enter=enter;if(hasText(leave))params.leave=leave;applyScrollSync(params,item);applyCallbacks(params,item.callbacks);applyAdvanced(params,item);registry.items[item.id]=onScroll(params);}}
      function svgUtil(name){{return anime.svg&&anime.svg[name]||anime[name];}}
      function textUtil(name){{return anime.text&&anime.text[name]||anime[name];}}
      function drawValue(value){{var text=String(value||'0 1').trim();if(text.indexOf(',')===-1)return text;return text.split(',').map(function(part){{return part.trim();}}).filter(Boolean);}}
      function splitPartOptions(split){{var hasOptions=hasText(split.className)||hasText(split.wrap)||split.clone;var options={{}};if(hasText(split.className))options.class=split.className;if(hasText(split.wrap))options.wrap=split.wrap;if(split.clone)options.clone=true;return hasOptions?options:true;}}
      function splitTextSettings(split){{split=split||{{}};var params={{}};if(split.lines)params.lines=true;if(split.words)params.words=splitPartOptions(split);if(split.chars)params.chars=splitPartOptions(split);if(split.includeSpaces)params.includeSpaces=true;if(split.accessible===false)params.accessible=false;if(split.debug)params.debug=true;return params;}}
      function scrambleSettings(scramble){{scramble=scramble||{{}};var params={{}};if(hasText(scramble.text))params.text=scramble.text;if(hasText(scramble.chars))params.chars=scramble.chars;if(typeof scramble.override==='boolean')params.override=scramble.override;if(hasText(scramble.ease))params.ease=scramble.ease;if(hasText(scramble.cursor))params.cursor=scramble.cursor;if(Number.isFinite(+scramble.revealRate))params.revealRate=+scramble.revealRate;if(Number.isFinite(+scramble.revealDelay))params.revealDelay=+scramble.revealDelay;if(Number.isFinite(+scramble.settleRate))params.settleRate=+scramble.settleRate;if(Number.isFinite(+scramble.settleDuration))params.settleDuration=+scramble.settleDuration;if(Number.isFinite(+scramble.delay))params.delay=+scramble.delay;if(Number.isFinite(+scramble.duration))params.duration=+scramble.duration;if(hasText(scramble.from))params.from=parseMaybeNumber(scramble.from);if(scramble.reversed)params.reversed=true;if(Number.isFinite(+scramble.perturbation))params.perturbation=+scramble.perturbation;if(Number.isFinite(+scramble.seed))params.seed=+scramble.seed;return params;}}
      function runSvg(item){{var target=readTarget(item);var params=applyPlayback({{}},item.playback);applyCallbacks(params,item.callbacks);if(item.mode==='morphTo'){{var morphTo=svgUtil('morphTo');if(!morphTo)return;params[item.attribute==='points'?'points':'d']=morphTo(item.source||item.path,Number.isFinite(+item.precision)?+item.precision:0.33);applyAdvanced(params,item);registry.items[item.id]=animate(target,params);return;}}if(item.mode==='createMotionPath'){{var createMotionPath=svgUtil('createMotionPath');if(!createMotionPath)return;var motion=createMotionPath(item.source||item.path||target,Number.isFinite(+item.offset)?+item.offset:0);Object.keys(motion||{{}}).forEach(function(key){{params[key]=motion[key];}});applyAdvanced(params,item);registry.items[item.id]=animate(target,params);return;}}var createDrawable=svgUtil('createDrawable');if(!createDrawable)return;params.draw=drawValue(item.draw);applyAdvanced(params,item);registry.items[item.id]=animate(createDrawable(item.source||item.path||target),params);}}
      function runText(item){{var target=readTarget(item);if(item.mode==='scrambleText'){{var scrambleText=textUtil('scrambleText');if(!scrambleText)return;var params={{innerHTML:scrambleText(scrambleSettings(item.scramble))}};applyCallbacks(params,item.callbacks);applyAdvanced(params,item);registry.items[item.id]=animate(target,params);return;}}var splitText=textUtil('splitText');if(!splitText)return;var splitParams=splitTextSettings(item.split);applyAdvanced(splitParams,item);registry.items[item.id]=splitText(target,splitParams);}}
      function runUtilities(item){{if(item.expression&&item.expression.enabled){{registry.items[item.id]=runExpression(item.expression,[anime,item,anime.utils||anime],null);return;}}if(item.utility==='stagger'){{var config=item.stagger||{{}};var options={{}};if(Number.isFinite(+config.start))options.start=+config.start;if(hasText(config.from))options.from=config.from;if(config.reversed)options.reversed=true;if(hasText(config.ease))options.ease=config.ease;if(hasText(config.grid)){{var grid=config.grid.split(/[,\sx]+/).map(Number).filter(Number.isFinite);if(grid.length>=2)options.grid=[grid[0],grid[1]];}}if(hasText(config.axis))options.axis=config.axis;if(Number.isFinite(+config.total)&&+config.total>0)options.total=+config.total;if(config.modifier&&config.modifier.enabled)options.modifier=runExpression(config.modifier,[anime,anime.utils||anime],undefined);registry.items[item.id]=stagger(+config.each||parseMaybeNumber(item.args)||0,options);return;}}var util=resolveUtil(item.utility);if(typeof util==='function')registry.items[item.id]=util.apply(null,parseArgs(item.args));}}
      function runEasing(item){{registry.items[item.id]=easingValue(item);}}
      function runWaapi(item){{if(!waapi||!waapi.animate)return;var params=applyPlayback(assignProps({{}},item.properties),item.playback);if(Number.isFinite(+item.iterations))params.iterations=+item.iterations;if(hasText(item.direction))params.direction=item.direction;if(hasText(item.easing)){{var ease=item.easing;if(item.convertEase&&waapi.convertEase)try{{ease=waapi.convertEase(ease);}}catch(error){{}}params.ease=ease;params.easing=ease;}}if(item.autoplay===false)params.autoplay=false;if(item.hardwareAcceleration)params.hardwareAcceleration=true;applyAdvanced(params,item);var animation=waapi.animate(readTarget(item),params);registry.items[item.id]=animation;if(item.finished&&item.finished.enabled&&animation&&animation.finished&&animation.finished.then)animation.finished.then(function(){{runExpression(item.finished,[animation,anime,anime.utils||anime],undefined);}});}}
      function runEngine(item){{if(!engine)return;if(hasText(item.timeUnit))engine.timeUnit=item.timeUnit;if(Number.isFinite(+item.speed))engine.speed=+item.speed;if(Number.isFinite(+item.fps))engine.fps=+item.fps;if(Number.isFinite(+item.precision))engine.precision=+item.precision;if(typeof item.pauseOnDocumentHidden==='boolean')engine.pauseOnDocumentHidden=item.pauseOnDocumentHidden;if(Number.isFinite(+item.priority)){{engine.defaults=engine.defaults||{{}};engine.defaults.priority=+item.priority;}}registry.items[item.id]=engine;}}
      function runInteraction(item){{var target=readTarget(item);document.addEventListener(item.event||'click',function(event){{var trigger=event.target&&event.target.closest?event.target.closest(target):null;if(!trigger)return;var nodes=document.querySelectorAll(item.targetSelector||target);nodes.forEach(function(node){{if(item.action==='toggleClass')node.classList.toggle(item.value);else if(item.action==='addClass')node.classList.add(item.value);else if(item.action==='removeClass')node.classList.remove(item.value);else if(item.action==='show')node.style.display='';else if(item.action==='hide')node.style.display='none';else if(item.action==='scrollTo')node.scrollIntoView({{behavior:'smooth'}});}});}});}}
      function runCustom(item){{registry.items[item.id]=runExpression({{enabled:true,label:item.name||'custom',code:item.code}},[anime,item,registry],null);}}
      function runItem(item){{if(!item||item.enabled===false)return;try{{if(item.type==='animation')runAnimation(item);else if(item.type==='timeline')runTimeline(item);else if(item.type==='timer')runTimer(item);else if(item.type==='animatable')runAnimatable(item);else if(item.type==='draggable')runDraggable(item);else if(item.type==='layout')runLayout(item);else if(item.type==='scope')runScope(item);else if(item.type==='scroll')runScroll(item);else if(item.type==='svg')runSvg(item);else if(item.type==='text')runText(item);else if(item.type==='utilities')runUtilities(item);else if(item.type==='easing')runEasing(item);else if(item.type==='waapi')runWaapi(item);else if(item.type==='engine')runEngine(item);else if(item.type==='interaction')runInteraction(item);else if(item.type==='custom')runCustom(item);}}catch(error){{warn(item,error);}}}}
      (motion.items||[]).forEach(runItem);
    }})();"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn motion_js_is_empty_without_motion_items() {
        let js = generate_motion_js(&PageJsConfig::default());
        assert!(js.is_empty());
    }

    #[test]
    fn motion_js_embeds_runtime_and_payload() {
        let config = PageJsConfig {
            version: Some(1),
            motion: Some(serde_json::json!({
                "schemaVersion": 1,
                "animeVersion": "4.4.1",
                "items": [{
                    "id": "animation-a",
                    "type": "animation",
                    "enabled": true,
                    "target": { "mode": "selector", "selector": ".hero-title" },
                    "properties": [],
                    "keyframes": [{
                        "id": "keyframe-a",
                        "label": "Intro",
                        "at": "50%",
                        "duration": 200,
                        "ease": "outQuad",
                        "properties": []
                    }]
                }]
            })),
            ..PageJsConfig::default()
        };

        let js = generate_motion_js(&config);
        assert!(js.contains("MOTION STUDIO"));
        assert!(js.contains("runAnimation"));
        assert!(js.contains("keyframeParams"));
        assert!(js.contains("\"id\":\"animation-a\""));
        assert!(js.contains("\"id\":\"keyframe-a\""));
        assert!(js.contains("\"selector\":\".hero-title\""));
    }

    #[test]
    fn motion_js_guards_timeline_self_sync() {
        let config = PageJsConfig {
            version: Some(1),
            motion: Some(serde_json::json!({
                "schemaVersion": 1,
                "animeVersion": "4.4.1",
                "items": [{
                    "id": "timeline-a",
                    "type": "timeline",
                    "enabled": true,
                    "steps": [{
                        "id": "step-a",
                        "type": "sync",
                        "targetItemId": "timeline-a",
                        "position": "0"
                    }]
                }]
            })),
            ..PageJsConfig::default()
        };

        let js = generate_motion_js(&config);
        assert!(js.contains("syncTarget.id===item.id"));
        assert!(js.contains("syncInstance&&syncInstance!==timeline"));
    }
}
